### ISSUE TITLE
HA minimal version requirement incorrect

### ISSUE THREAD

**Issue by joostvkempen** [pawkakol1/worlds-air-quality-index#11]
Tried updating to 0.3.0, got this error:

![image](https://user-images.githubusercontent.com/37901988/172239072-c3a642ab-57f1-4887-9ffc-86d21653235f.png)

translation: You're using HA version '2022.6.2', this repository requires minimal version 'core-2022.5.5' installed.

I'm running HA in Docker container, version numbering on that does not include 'core' prefix, maybe that's causing an error?

**Comment by pawkakol1** [comment]
Fixed in release v0.3.2
