### ISSUE TITLE
update to 0.3.2 failed.

### ISSUE THREAD

**Issue by bakboord4** [pawkakol1/worlds-air-quality-index#12]
Tried to update to 0.3.2.

None of the sensors are available.

Failed due to:

Logger: homeassistant.config_entries
Source: config_entries.py:549 
First occurred: 23:10:25 (1 occurrences) 
Last logged: 23:10:25

Migration handler not found for entry luchtkwalitetbuiten for worlds_air_quality_index

## System Health

version | core-2022.6.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.12
os_name | Linux
os_version | 5.15.32-v8
arch | aarch64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4236
Installed Version | 1.25.5
Stage | running
Available Repositories | 1122
Downloaded Repositories | 24

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.1
-- | --
update_channel | beta
supervisor_version | supervisor-2022.05.3
agent_version | 1.2.1
docker_version | 20.10.14
disk_total | 111.1 GB
disk_used | 8.9 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Check Home Assistant configuration (3.10.0), File editor (5.3.3), Mosquitto broker (6.1.2), Samba Backup (5.0.0), Samba share (9.6.1), Z-Wave JS to MQTT (0.42.0), Terminal & SSH (9.4.0), AppDaemon (0.8.2), ESPHome (2022.5.1), Filebrowser (2.22.0), AdGuard Home (4.5.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 16
views | 7
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 30 mei 2022 13:47
-- | --
current_recorder_run | 6 juni 2022 23:10
estimated_db_size | 206.70 MiB
database_engine | sqlite
database_version | 3.34.1

</details>

**Comment by ecto1a2003** [comment]
same here for 

Logger: homeassistant.config_entries
Source: config_entries.py:549
First occurred: 4:57:01 PM (1 occurrences)
Last logged: 4:57:01 PM

Migration handler not found for entry upland_san_bernardino for worlds_air_quality_index

**Comment by LinusHoppe** [comment]
Same here:
```
Logger: homeassistant.config_entries
Source: config_entries.py:549
First occurred: 07:40:12 (1 occurrences)
Last logged: 07:40:12

Migration handler not found for entry WAQI for worlds_air_quality_index
```
Seems to be introduced with [https://github.com/pawkakol1/worlds-air-quality-index/commit/84349f040fc1a611566ea0021d37629ed7be1a5b](https://github.com/pawkakol1/worlds-air-quality-index/commit/84349f040fc1a611566ea0021d37629ed7be1a5b) by changing `VERSION` from `1` to `2`.
You need a migration handler as mentioned [here](https://developers.home-assistant.io/docs/config_entries_config_flow_handler/#config-entry-migration).

**Comment by pawkakol1** [comment]
I will try to add migrator today.
Workaround for it is delete integration from HA (in Devices and Services) and then add it again, but it is good if you didn't change names and ids of entities of your station - workaround will delete your changes.

**Comment by bakboord4** [comment]
@pawkakol1. Installed version 0.3.3.
All sensors are showing values again.
For me this issue can be closed.
Thank you for the time and energy spent to solve  this issue successfully.

**Comment by pawkakol1** [comment]
DONE in release 0.3.3
