### ISSUE TITLE
Showing temperature in Celsius

### ISSUE THREAD

**Issue by nolageek** [pawkakol1/worlds-air-quality-index#15]
Showing temperature in Celsius no matter what I set the unit to, even when Imperial is configured as default.

**Comment by pawkakol1** [comment]
@nolageek I published prerelease [v0.3.4-beta1](https://github.com/pawkakol1/worlds-air-quality-index/releases/tag/v0.3.4-beta1), I didn't know about some details of your issue:
- is it show about **21 deg C** (standard temperature value in Celsius with Celsius unit) or is it show about **70 deg C** (standard temperature value in Fahrenheit with Celsius unit)?

Could you install this prerelease and confirm, that it works proper for you?

To show prereleases in HACS you need to click "redownload", and then turn on "Show Beta Versions"
![image](https://user-images.githubusercontent.com/69692263/173416174-2b4de669-c0dc-4cbc-9ec8-4cc1e0979c75.png)

**Comment by pawkakol1** [comment]
@nolageek does it work for you now?

**Comment by pawkakol1** [comment]
@nolageek due to no answers from you it will be released in next release
