### ISSUE TITLE
Wrong units

### ISSUE THREAD

**Issue by pipacsba** [pawkakol1/worlds-air-quality-index#19]
Most of the sensors are showing ug/m3 as unit_of_measurement. I think waqi provides the values in some strange 1-500 AQI Levels.
https://www.airnow.gov/sites/default/files/2020-05/aqi-technical-assistance-document-sept2018.pdf

Best would be to transfer back (at least optionally) to ug/m3, but I think the proper unit should be shown.

**Comment by wBrhy2** [comment]
We have the same issue in Ontario Canada, where the PM2.5 is converted to AQI. We would need to be able to override the unit or measurement or revert it to ug/m3

**Comment by pawkakol1** [comment]
Unfortunately AQI value range between 1-500 is generated by WAQI, and then exposed in their REST API. AQI scale is based on [US EPA standard](https://www.epa.gov/environmental-topics/air-topics), and it uses [Instant Cast](https://aqicn.org/faq/2015-03-15/air-quality-nowcast-a-beginners-guide/) reporting formula, which is described on main page of WAQI web site.
The US EPA standard predicts formula based on 24-hour average data to calculate AQI, so I'm not able to recalculate AQI value get from their RES API to current value in ug/m3.
I need to close this issue.
