### ISSUE TITLE
select a station by id

### ISSUE THREAD

**Issue by joostvkempen** [pawkakol1/worlds-air-quality-index#2]
It would be a nice feature to choose a station not by longitude/latitude, but by station ID (f.e. https://aqicn.org/station/@126175)

**Comment by pawkakol1** [comment]
I will add possibility to integrate station using its ID, on this week

**Comment by joostvkempen** [comment]
Terrific! there's one around the corner, however the integration keeps picking one kilometres away from here.... Using the station ID will hopefully fix this

**Comment by pawkakol1** [comment]
Waqi API isn't allow to get this station, because it is station from external web site  openmap.clarity.io
I will use scrape method for those stations, what aren't support by API

**Comment by grossqx** [comment]
awesome! I have the same issue. looking forward to the update. thank you for your work

**Comment by pawkakol1** [comment]
Release v0.3.0
