### ISSUE TITLE
compared to core integration?

### ISSUE THREAD

**Issue by Mariusthvdb** [pawkakol1/worlds-air-quality-index#20]
HI,
please let me ask what the difference with the core integration for Waqi is https://www.home-assistant.io/integrations/waqi/ besides the config flow?

Id be happy to test if this CC would be more informative or more stable than core.

thanks!

**Comment by pawkakol1** [comment]
Hi @Mariusthvdb,
I will write waqi about official integration, and worlds_air_quality_index about this HACS integration.
Below several differences:
- waqi is integrated using configuration.yaml file; worlds_air_quality_index is integrated using UI: Devices&Services -> AddIntegration
- waqi stations are added as a single sensor entities, where main value is AQI, and rest station values are attributes of this sensor; worlds_air_quality_index stations are added as a service with entities (for each station's values it creates separate sensor entity)
- for waqi you need to put location as a name (e.g. name of city/town), and it will integrate all stations contained this phrase in my case if I put name of my city it will show all stations in my city, and additionally stations of 3 towns near this city, and you aren't able to delete stations you aren't interested to have, you are able to disable them only; 
for worlds_air_quality_index you have 3 options: it will get your home's geo coords, you can put your own geo coords (and it will find the closest only one station in both cases), you can put ID of station, all added stations you can delete one by one
- neither waqi nor worlds_air_quality_index don't support stations, what has ID higher than 13837.
- waqi is updating values every 5 minutes; worlds_air_quality_index is updating values every 30 minutes; waqi.info site is updating stations every 60 minutes, so refreshing so often (like waqi does) doesn't make sense, and it overloads servers of free service.
- I saw that waqi (propably) supports Wind's Gauge; worlds_air_quality_index  doesn't support it, but I will investigate it, and if API supports it I will add it for worlds_air_quality_index 

I don't know any more differences

**Comment by pawkakol1** [comment]
@Mariusthvdb in case of supported stations ID look on this comment
https://github.com/pawkakol1/worlds-air-quality-index/issues/10#issuecomment-1276670492
Wind Gauge sensor will be supported in next release (I will do it tomorrow or on Friday)

**Comment by Mariusthvdb** [comment]
Thank you Pawel,

for your explanation. Looking forward to giving it a test drive.
cheers!
