### ISSUE TITLE
How to get station ID?

### ISSUE THREAD

**Issue by PrzemekSkw** [pawkakol1/worlds-air-quality-index#21]
I try to install that integration in my HA but there's no instructions how to find station ID. I go to my station website and there's nothing about ID.
Regards.

**Comment by pawkakol1** [comment]
You need to find your station on waqi.info:
![image](https://user-images.githubusercontent.com/69692263/177040986-771aa23b-c95f-42a3-9346-fd282d0692b3.png)
then double click on sign of your station, it will forward you into aqicn.org. On new website scroll down until huge "Looking for another city?" is shown. Then find hyperlink above this sentence like on below image:
![image](https://user-images.githubusercontent.com/69692263/177041249-f0842b2a-658b-489c-ab34-cc3a83d32782.png)
ID of your station is after @ char.

I will add this description to Readme file in next release

**Comment by PrzemekSkw** [comment]
OK, thanks for help.
