### ISSUE TITLE
Change air quality index value to integer

### ISSUE THREAD

**Issue by FragMenthor** [pawkakol1/worlds-air-quality-index#22]
The main air quality index appears in HA as a discrete value, should be an integer, so it can be charted correctly.

![Screenshot_2022-07-03-03-32-55-541_io homeassistant companion android](https://user-images.githubusercontent.com/74264069/177022212-7f2121ac-3f1a-4e3d-b898-417ff5f9fd04.jpg)

Thanks in advance, and thank you for this integration!

**Comment by pawkakol1** [comment]
Do you mean, you want to have discrete chart likewise on below example?
![image](https://user-images.githubusercontent.com/69692263/177041569-b827b52d-4101-49bc-937e-ec17a042e8d7.png)

**Comment by FragMenthor** [comment]
> Do you mean, you want to have discrete chart likewise on below example? ![image](https://user-images.githubusercontent.com/69692263/177041569-b827b52d-4101-49bc-937e-ec17a042e8d7.png)

Yes ☺️😃 🙏
I know I can make a sensor template to convert, but it's pretty unusable like it is!

**Comment by pawkakol1** [comment]
Ok, I'll try to do it in next release

**Comment by pawkakol1** [comment]
@FragMenthor
@bsegault contributor did it, I will release it tomorrow or on Friday

**Comment by FragMenthor** [comment]
Thanks!😉😊
