### ISSUE TITLE
 It does not show other data

### ISSUE THREAD

**Issue by jrousek** [pawkakol1/worlds-air-quality-index#23]
Why doesn't the station show the other data?

Station 2768

show only:
air_quality_index
particulate_matter_pm10

But the station has other data:

{"status":"ok","data":{"aqi":30,"idx":2768,"attributions":[{"url":"https://portal.chmi.cz/","name":"Czech Hydrometeorological Institute (Český hydrometeorologický ústav)","logo":"CzechRepublic-CHMU.png"},{"url":"https://waqi.info/","name":"World Air Quality Index Project"}],"city":{"geo":[50.042198055556,15.739414166667],"name":"Pardubice-Rosice, Pardubicky, Czech Republic","url":"https://aqicn.org/city/czechrepublic/pardubicky/pardubice-rosice","location":""},"dominentpol":"pm25","iaqi":**_{"dew":{"v":10},"h":{"v":82},"no2":{"v":6.9},"o3":{"v":4.7},"p":{"v":1026},"pm10":{"v":9},"pm25":{"v":30},"so2":{"v":0.7},"t":{"v":13},"w":{"v":1.5},"wg":{"v":8.7}}_**,"time":{"s":"2022-07-18 07:00:00","tz":"+02:00","v":1658127600,"iso":"2022-07-18T07:00:00+02:00"},"forecast":{"daily":{"o3":[{"avg":27,"day":"2022-07-16","max":35,"min":16},{"avg":24,"day":"2022-07-17","max":34,"min":13},{"avg":25,"day":"2022-07-18","max":38,"min":14},{"avg":30,"day":"2022-07-19","max":45,"min":20},{"avg":31,"day":"2022-07-20","max":47,"min":20},{"avg":25,"day":"2022-07-21","max":25,"min":23}],"pm10":[{"avg":7,"day":"2022-07-16","max":10,"min":4},{"avg":7,"day":"2022-07-17","max":8,"min":5},{"avg":9,"day":"2022-07-18","max":11,"min":7},{"avg":10,"day":"2022-07-19","max":13,"min":9},{"avg":11,"day":"2022-07-20","max":12,"min":10},{"avg":12,"day":"2022-07-21","max":12,"min":11}],"pm25":[{"avg":23,"day":"2022-07-16","max":38,"min":14},{"avg":18,"day":"2022-07-17","max":24,"min":14},{"avg":28,"day":"2022-07-18","max":36,"min":20},{"avg":31,"day":"2022-07-19","max":38,"min":28},{"avg":34,"day":"2022-07-20","max":37,"min":29},{"avg":35,"day":"2022-07-21","max":39,"min":35}],"uvi":[{"avg":1,"day":"2022-07-16","max":4,"min":0},{"avg":1,"day":"2022-07-17","max":7,"min":0},{"avg":1,"day":"2022-07-18","max":7,"min":0},{"avg":1,"day":"2022-07-19","max":7,"min":0},{"avg":1,"day":"2022-07-20","max":7,"min":0},{"avg":1,"day":"2022-07-21","max":6,"min":0},{"avg":1,"day":"2022-07-22","max":5,"min":0}]}},"debug":{"sync":"2022-07-18T15:37:43+09:00"}}}

**Comment by Norbator** [comment]
I had the same problem with another station just after installing & setting up the custom component. But several minutes (>30mn?) later all the data were well filled in.

**Comment by pawkakol1** [comment]
@jrousek and @Norbator 
When you add your station you will see 2 or 3 entities only like on below screen:
![image](https://user-images.githubusercontent.com/69692263/195433575-ae73fffa-52e6-4b61-b160-d780b725e2b5.png)
But when you will refresh Web Browser card using CTRL+F5 it will show all others entities:
![image](https://user-images.githubusercontent.com/69692263/195432678-d8792216-d7a9-477e-955d-5a22d3fc3e06.png)
I don't know why it behaves like that, I noticed it for some others integrations, but it works.

**Comment by tuimz** [comment]
Can I re-open this?

I have selected a station that has more data, added the integration yesterday and still have only:

![image](https://user-images.githubusercontent.com/850235/199207714-727a89d2-1cd7-442a-9429-b59d2ab6c5c3.png)

**Comment by pawkakol1** [comment]
@tuimz 
Firtstly try to check if API supports more info than you expected:
waqi.info shows data like below:
![image](https://user-images.githubusercontent.com/69692263/199267989-b5e1744c-0518-42a8-8f05-21cda5479970.png)
But if you will check available API:
![image](https://user-images.githubusercontent.com/69692263/199268229-bccd14e6-9807-42c5-bdda-f26db8773c57.png)
Then you can see that its API doesn't support all shown data (it supports PM10 and PM25 only):
![image](https://user-images.githubusercontent.com/69692263/199267329-cd6fc48d-aa8f-4ead-8e70-a6bf32eab10c.png)

**Comment by tuimz** [comment]
Thanks, I didnt know that! I figured they would show all info.
Thats unfortunate.
