### ISSUE TITLE
Unable to add integration from UI

### ISSUE THREAD

**Issue by FragMenthor** [pawkakol1/worlds-air-quality-index#29]
Hello.
At some point I lost the ability to add this integration in the UI, it reports that the configuration should be done in configuration.yaml... What am I doing wrong, or what am I missing?
Using all latest versions, HA 2022.10.5 and your integration 3.4

![Captura de ecrã 2022-10-21 094008](https://user-images.githubusercontent.com/74264069/197153723-1cb5b3fe-c10e-4690-acd9-0803eefd835c.png)
![Captura de ecrã 2022-10-21 093942](https://user-images.githubusercontent.com/74264069/197153727-e3d5f174-9b09-4b41-ae18-d6ce60803927.png)

Btw, I need to get information from this station:

https://api.waqi.info/feed/A191107/?token={token}

How should I add it, please? Thanks in advance!

**Comment by FragMenthor** [comment]
Well, I completly removed the integration and installed again, and it seams to work, so I will close this.
I am trying to get the values from this station:

https://aqicn.org/station/portugal/senhora-da-sa%C3%BAde/rua-de-dom-manuel-da-concei%C3%A7%C3%A3o-santos/
I can get info from
https://api.waqi.info/feed/A191107/?token={token}
and i got, for instance:
```
{"status":"ok","data":{"aqi":0,"idx":-191107,"attributions":[{"url":"https://uradmonitor.com/","name":"uRad Monitor","station":"820002a8"},{"url":"https://waqi.info/","name":"World Air Quality Index Project"}],"city":{"geo":[38.5667,-7.9],"name":"Rua de Dom Manuel da Conceição Santos","url":"https://aqicn.org/station/@191107","location":"Rua de Dom Manuel da Conceição Santos, Álamos, Senhora da Saúde, Bacelo e Senhora da Saúde, Évora, Alentejo Central, Alentejo, 7005-451, Portugal"},"dominentpol":"pm25","iaqi":{"h":{"v":54.42},"o3":{"v":8},"p":{"v":989.07},"pm10":{"v":0},"pm25":{"v":0},"t":{"v":26.77}},"time":{"s":"2022-10-21 11:57:57","tz":"+01:00","v":1666349877,"iso":"2022-10-21T10:57:57Z"}}}
```

When I added the integration again I can get to some of the station data, but not the AQI:

![image](https://user-images.githubusercontent.com/74264069/197162439-23929c7c-97db-4414-8b29-ce251126c746.png)



Any ideas?
Thanks again :)

**Comment by pawkakol1** [comment]
You tried to add original integration named "World Air Quality Index (WAQI)", this integration is named "World's Air Quality Index" - try to add it again with below instructions:
![image](https://user-images.githubusercontent.com/69692263/199265818-c6612af0-6643-4ed6-b419-f10af183eab0.png)

**Comment by FragMenthor** [comment]
Nope, my integration is yours:

![image](https://user-images.githubusercontent.com/74264069/199523707-6df710bf-0a21-4aca-91fb-d49733255746.png)

I think my problems comes from constant error from the api, sometimes I get the value, most frequently I don't.

**Comment by pawkakol1** [comment]
@FragMenthor 
I just added it (using Station ID A191107) and it added AQI entity for me
![image](https://user-images.githubusercontent.com/69692263/199616598-75e20abb-f77a-43ec-95b1-53b458db7e9d.png)
Could you check below:
- delete integration and add it using Station ID (A191107)?
- change language to english (for test), and check?
- off course you have the newest v0.3.5 release installed?
- check hide/disable entities?
