### ISSUE TITLE
string indices must be integers

### ISSUE THREAD

**Issue by Anian-igor** [pawkakol1/worlds-air-quality-index#31]
Home Assistant 2022.10.5
worlds-air-quality-index 0.3.5
Idx:A252880
http://aqicn.org/station/ukraine/pecherskyi-district/44a/vulytsia-yevhena-konovaltsia/

I got this issue from yesterday
`2022-11-03 16:59:52.563 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up worlds_air_quality_index platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/worlds_air_quality_index/sensor.py", line 106, in async_setup_entry
    scannedData = scannedData["data"]["iaqi"]
TypeError: string indices must be integers`

**Comment by pawkakol1** [comment]
Did you update the existed device/service or did you just add new station to your HA?

**Comment by Anian-igor** [comment]
I found that station was closed. That's why I got an issue.
