### ISSUE TITLE
The integration will fail in 2023.3.

### ISSUE THREAD

**Issue by henrikbla** [pawkakol1/worlds-air-quality-index#34]
Log says the following:

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for worlds_air_quality_index using this method at custom_components/worlds_air_quality_index/__init__.py, line 30: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by pawkakol1** [comment]
@henrikbla, thanks I will fix it before 2023.3

**Comment by pawkakol1** [comment]
Done by @ejpenney, merged to main branch

**Comment by henrikbla** [comment]
Don't forget to publish a new version before Wednesday :).

**Comment by pawkakol1** [comment]
Done and released
https://github.com/pawkakol1/worlds-air-quality-index/releases/tag/v1.0.0
