### ISSUE TITLE
Wrong station by location coordinates

### ISSUE THREAD

**Issue by jjmuriel** [pawkakol1/worlds-air-quality-index#4]
HI,
I live in Cali, Colombia and I want to configure the station of my city that has the ID @254464 (https://aqicn.org/station/@254464), but the integration set a station from Bogotá, Colombia (ID: @8512).  I set the exact coordinates of the station that I want, but I can not configure the integration .  There is a way to configure the integration by station ID?

**Comment by pawkakol1** [comment]
I will add possibility to integrate station using its ID, on this week.

**Comment by jjmuriel** [comment]
Thank you!

**Comment by pawkakol1** [comment]
I tried to get your 254464 station using API, and it says, that this ID doesn't exist:
![image](https://user-images.githubusercontent.com/69692263/171498728-f5057dd1-86d5-438e-a305-0d06f059ee5f.png)
When I tried to get 8512 with the same API, it receives data
![image](https://user-images.githubusercontent.com/69692263/171499182-b4c95972-045c-4e34-979d-b8f4d2a5f106.png)

I noticed, it depends on below example info placed under "Looking for another city?" header of choosen station:
```
This station real-data data API can be accessed from this url:
https://api.waqi.info/feed/@8512/?token=**************************************************
```
If there isn't info about real-data API, then it won't be able to get using this integration.
In case of station 254464 there is info (under "Looking for another city?" header), that this station is:
`Station [d29ttgotd906be] from [CanAir.IO](https://canair.io/) - https://canair.io/`
so you can use CanAirIo Home Assistant integration to use this station.

OffCourse I will add possibility possibility to integrate station using its ID, but I will extend description of this integration, that part of stations of waqi.info don't support their build-in API.

**Comment by jjmuriel** [comment]
I understand, thank you for the explanation. I'll try with CanAirIo Home Assistant integration.

**Comment by pawkakol1** [comment]
@jjmuriel I noticed that WAQI API supports some other stations (CanAir.IO or Citzen Science) too now. They added it to their API. If you want, you can integrate station 254464, but you need to put its ID as A254464
![image](https://user-images.githubusercontent.com/69692263/195426553-781824f6-6edc-4671-ba7d-69f5505b3f3e.png)

**Comment by jjmuriel** [comment]
Thank you for the info @pawkakol1. I'll test again.
