### ISSUE TITLE
Wind Direction is actually Wind Gust

### ISSUE THREAD

**Issue by wayned1014** [pawkakol1/worlds-air-quality-index#41]
The data being collected from the API call labeled 'wg' is wind gust not wind direction.

Thanks

**Comment by pawkakol1** [comment]
Thank you for report, I will try to fix that in the next week

**Comment by wayned1014** [comment]
I already have a pull request with the changes.

Thanks

**Comment by pawkakol1** [comment]
Fixed in and released as v1.0.2
