### ISSUE TITLE
Only creating 2 entities

### ISSUE THREAD

**Issue by JonScaife** [pawkakol1/worlds-air-quality-index#44]
Hi
I have set this fo rmy location (Sheffield UK) by lat and long.  It appears to find the right station ID of 5021 which corresponds to
https://api.waqi.info/feed/united-kingdom/sheffield-devonshire-green/?token=

However I only get a sensor for PM10

The station reports lots of other data e.g. PM2.5 and NO2

Any idea why these other data are not being detected?

**Comment by pawkakol1** [comment]
After adding the station there were PM10 and AQI index only,
but I refreshed window in 2-3 minutes, and I got
![image](https://github.com/pawkakol1/worlds-air-quality-index/assets/69692263/6aebdfd4-d010-4648-af0d-ae23c5c41b22)
