### ISSUE TITLE
some sensors missing

### ISSUE THREAD

**Issue by tomj44300** [pawkakol1/worlds-air-quality-index#7]
hi thanks for great integration.
i have some sensors like CO who missing
![Capture d’écran du 2022-06-02 16-50-06](https://user-images.githubusercontent.com/105393025/171657398-e8df4fd7-d787-46b4-95ef-4b3f80a28007.png)

**Comment by pawkakol1** [comment]
Hi, could you give me station ID?

**Comment by tomj44300** [comment]
I don't know how find station ID , it s Nantes La bouteillerie , town center 
https://aqicn.org/city/france/loire/nantes/bouteillerie/fr/

**Comment by tomj44300** [comment]
sorry i have find why , there is no CO sensors
official source
![Capture d’écran du 2022-06-02 17-20-01](https://user-images.githubusercontent.com/105393025/171663770-8dc83548-8c52-4619-b24f-7bb6037fc74f.png)

from aqi website
![Capture d’écran du 2022-06-02 17-20-44](https://user-images.githubusercontent.com/105393025/171663716-fad0d633-c633-4916-bf1d-9c3105983ef6.png)
