### ISSUE TITLE
Please, help me..

### ISSUE THREAD

**Issue by PioSkot** [pawkakol1/worlds-air-quality-index#8]
When I try to connect the sensor without entering the option (only the token) or by entering my geographic location, the sensor from Sucha Beskidzka (100 km from me) is connected. WAQI shows the measuring station at my place (Jaworzno). How can I identify it?

https://aqicn.org/station/@240451pl//#/z/16.3

**Comment by pawkakol1** [comment]
waqi.info web API supports stations with IDs between 1 and 13837 only. If your station has ID greater than 13837 it won't be able to add using station ID method (what I develop right now) nor geolocalized coordinates method. In the future waqi.info web API would be developed, and there would be more supported stations, but we don't know that for sure. You can always check if your station is supported. You just need to copy below link, paste to the URL of web browser, change number of interested station, and paste your token instead {{token}}

https://api.waqi.info/feed/@13837/?token={{token}}

Web browser will receive some data, if station is supported or "Unknown ID" message, if it doesn't.
